./tb/Final_tb.v
./src_L2Cache/CHIP.v
./tb/slow_memory.v
./src_L2Cache/HandleHazard.v
./src_L2Cache/MIPS_Pipeline.v
./src_L2Cache/cache_2way_L2.v
./src_L2Cache/ALU.v
./src_L2Cache/ALU_CONTROL.v
./src_L2Cache/CONTROL.v
./src_L2Cache/REGISTER.v