./tb/Final_tb.v
./src_BrPred/CHIP.v
./tb/slow_memory.v
./src_BrPred/MIPS_Pipeline.v
./src_BrPred/cache.v   
./src_BrPred/ALU_CONTROL.v  
./src_BrPred/BrPred.v  
./src_BrPred/HandleHazard.v   
./src_BrPred/REGISTER.v
./src_BrPred/ALU.v          
./src_BrPred/CONTROL.v