./tb/Final_tb.v
./src/CHIP.v
./tb/slow_memory.v
./src/HandleHazard.v
./src/MIPS_Pipeline.v
./src/cache.v
./src/ALU.v
./src/ALU_CONTROL.v
./src/CONTROL.v
./src/REGISTER.v
./src/Multiplier/Iter32_mult.v
./src/Multiplier/Iter8_mult.v
./src/Multiplier/Iter4_mult.v
./src/Multiplier/Iter1_mult.v
./src/Divider/Iter_div.v