./tb/Final_tb.v
./src_extension/CHIP.v
./tb/slow_memory.v
./src_extension/HandleHazard.v
./src_extension/MIPS_Pipeline.v
./src_extension/cache_2way_L2.v
./src_extension/ALU.v
./src_extension/ALU_CONTROL.v
./src_extension/CONTROL.v
./src_extension/REGISTER.v
./src_extension/BrPred.v
./src_extension/Multiplier/Booth_mult.v
./src_extension/Divider/Iter_div.v